language: cpp
compiler: clang
before_install:
            - sudo apt-get update -qq
install:
            - sudo apt-get install -qq dh-autoreconf libjsoncpp-dev libcurl4-gnutls-dev libncurses5-dev
            - wget http://mirrors.kernel.org/ubuntu/pool/main/a/autoconf/autoconf_2.69-6_all.deb
            - sudo dpkg -i autoconf_2.69-6_all.deb
before_script:
            - ./autogen.sh
script:
            - ./configure && make -I /usr/include/jsoncpp
